# .streamlit/secrets.toml
SUPABASE_URL = "https://qiafwyuzcmqoqxhzqcjq.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpYWZ3eXV6Y21xb3F4aHpxY2pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTk2MTcsImV4cCI6MjA2MzM5NTYxN30.Htl8pvbB21SLNDIl9W6h7yAbGpZPAu1nRlK5no3uBYY"
